### ISSUE TITLE
cant download any files

### ISSUE THREAD

**Issue by scrimpy** [finalmakerr/featherence#110]
15:37:45.417 T:8572  NOTICE: Featherence Emu: !@# DownloadFile_LV14 returned: skip
                                            url: https://www.dropbox.com/s/liq3qlqvjef9yjm/Nintendo%2064_2P.zip?dl=1
                                            downloadpath: C:\Users\AppData\Roaming\Kodi\cache\
                                            downloadpath2: C:\Users\AppData\Roaming\Kodi\cache\Nintendo 64_2P.zip
                                            extractpath: C:\Users\AppData\Roaming\Kodi\userdata\addon_data\emulator.retroarch\rom\
                                            silent: False

**Comment by scrimpy** [comment]
kodi 17.3 windows and libreelec

**Comment by scrimpy** [comment]
15:50:45.949 T:8428  NOTICE: Featherence Emu: !@# DownloadFile_LV134 returned: ok
                                            url: https://www.dropbox.com/s/ccaqjedfl22e3ul/Arcade_2P.zip?dl=1
                                            downloadpath: C:\Users\AppData\Roaming\Kodi\cache\
                                            downloadpath2: C:\Users\AppData\Roaming\Kodi\cache\Arcade_2P.zip
                                            extractpath: C:\Users\AppData\Roaming\Kodi\userdata\addon_data\emulator.retroarch\rom\
                                            silent: False

some are working. i've read theres is an update to 1.4, because this seems to be 1.3. but it wont update

**Comment by scrimpy** [comment]
oh ok mirrors seem to be deleted by dropbox

**Comment by finalmakerr** [comment]
Thanks for the info!
It's working through the addon.
