### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by boltron88** [finalmakerr/featherence#111]
Hi there, downloads don't seem to be working for PlayStation or Nintendo currently, anything I could try?

**Comment by finalmakerr** [comment]
Tomorrow I will issue new update that will tell you why you can't download a specific file.
Usually it's related to max traffic which is very annoying on Dropbox but it's auto solve after few days and then again ;(
Some files have multi sources but it's not enough to keep up with the demand..

Google drive would be great but I have no time to upload it and i find it difficult to download Google drive files from within Kodi atm ..

**Comment by eranavni** [comment]
How about using HFS ?
It works great for me when i share my tvguide file with it and you can get
a direct link to files
Google Drive have limit on the number of downloads after a while they block
it altho you can create a direct link to files stored in google drive.

2017-09-10 23:34 GMT+03:00 finalmakerr <notifications@github.com>:

**Comment by finalmakerr** [comment]
Eran thank you for your suggestion friend.
Maybe in the future i will manage to add support for that but someone will have to upload everything and share the links lol

**Comment by finalmakerr** [comment]
If someone could be so kind to help us , we may have another source for downloading which is Google Drive.

https://github.com/finalmakerr/featherence/blob/master/master/script.featherence.service/resources/lib/shared/commondownloader.py

Trigger by:
DownloadFile module in:
https://github.com/finalmakerr/featherence/blob/master/master/script.featherence.service/resources/lib/shared/shared_modules.py

The code must be configure to downloading chunks size = 32768.

**Comment by herogab** [comment]
> Tomorrow I will issue new update that will tell you why you can't download a specific file.
> Usually it's related to max traffic which is very annoying on Dropbox but it's auto solve after few days and then again ;(
> Some files have multi sources but it's not enough to keep up with the demand..
> 
> Google drive would be great but I have no time to upload it and i find it difficult to download Google drive files from within Kodi atm .. 



 https://www.multcloud.com with that you can easy transfere data from a cloud to another but it have a limite after you need paid mega is a good source cause you have a free 50 cloud storage

**Comment by finalmakerr** [comment]
Google Drive support is on the way 🙏
